"""Render the Proxmox installer answer file (answer.toml) from snap.yaml.

Design 0001, section 7.1, step 4. The builder puts this file inside the
Proxmox ISO, and the installer installs without asking anything. Key names follow
the Proxmox VE 9 automated installer; CI checks the output with the pinned
proxmox-auto-install-assistant.
"""

from __future__ import annotations

import json
from typing import Any

HEADER = "# Generated by snaplab from snap.yaml. Edit snap.yaml and regenerate instead of editing this file.\n"


def render(cfg: dict[str, Any]) -> str:
    """Return answer.toml for an already validated config."""
    host = cfg["host"]
    sections: list[tuple[str, dict[str, Any]]] = [
        (
            "global",
            {
                "keyboard": host["keyboard"],
                "country": host["country"],
                "fqdn": f"{host['hostname']}.{host['domain']}",
                "mailto": host["email"],
                "timezone": host["timezone"],
                "root-password-hashed": host["root_password_hash"],
            },
        ),
        ("network", _network(host["management"])),
        ("disk-setup", _disk(host)),
        # The handoff script is baked into the ISO at build time (Design 0001, section 7.5).
        ("first-boot", {"source": "from-iso", "ordering": "fully-up"}),
    ]
    out = [HEADER]
    for name, values in sections:
        out.append(f"\n[{name}]\n")
        out.extend(f"{key} = {_value(v)}\n" for key, v in values.items())
    return "".join(out)


def _network(mgmt: dict[str, Any]) -> dict[str, Any]:
    if mgmt["mode"] == "dhcp":
        return {"source": "from-dhcp"}
    return {
        "source": "from-answer",
        "cidr": mgmt["address"],
        "gateway": mgmt["gateway"],
        # The installer takes a single DNS server; the rest are set by CRACKLE.
        "dns": mgmt["dns"][0],
        # udev names a port enx<mac> by its MAC address, so this matches exactly one port.
        "filter.ID_NET_NAME_MAC": "*" + mgmt["mac"].replace(":", ""),
    }


def _disk(host: dict[str, Any]) -> dict[str, Any]:
    disk = host["target_disk"]
    values: dict[str, Any] = {"filesystem": host.get("storage", {}).get("filesystem", "ext4")}
    if "serial" in disk:
        values["filter.ID_SERIAL_SHORT"] = disk["serial"]
    else:
        values["filter.ID_MODEL"] = disk["model"]
    return values


def _value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        # A JSON string is a valid TOML basic string.
        return json.dumps(v, ensure_ascii=False)
    if isinstance(v, list):
        return "[" + ", ".join(_value(x) for x in v) + "]"
    raise TypeError(f"cannot write {type(v).__name__} to TOML")
